sudo: false
language: csharp
mono:
  - latest
  - 3.12.0
addons:
  apt:
    packages:
      - automake
      - libnunit-cil-dev
      - nunit-console
      - libglib2.0-cil-dev
      - pulseaudio
      - libpulse-dev
      - pulseaudio-utils
      - alsa-utils
script:
  - autoreconf -v -i
  - ./configure
  - make
  - make check

